version: '3.5'
services:
  node_prod:
    container_name: storage_node_prod
    build: node/
    restart: always
    environment:
      - ENV=prod
    networks:
      - prod
    volumes:
      - "./storage:/app/storage"
networks:
  prod:
    name: prod
    driver: bridge