version: '3.5'
services:
  node_test:
    container_name: storage_node_test
    build: node/
    environment:
      - ENV=test
    networks:
      - test
    volumes:
      - "./storage/node/test:/app/storage"
networks:
  test:
    external:
      name: test
    