version: '3'
services:
  node_prod:
    container_name: storage_node_prod
    build: node/
    restart: always
    ports:
      - 80:80
    environment:
      - ENV=prod
    networks:
      - prod
    volumes:
      - "./storage:/app/storage"
networks:
  prod:
    driver: bridge