version: '3'
services:
  node_test:
    container_name: storage_node_local
    build: node/
    ports:
      - 82:80
    volumes:
      - "./storage:/app/storage"
    networks:
      - local
networks:
  local:
    driver: bridge
